### ISSUE TITLE
Remove functions from sobol_seq.py

### ISSUE THREAD

**Issue by alchemyst** [Stefan-Endres/shgo#10]
There are functions in sobol_seq.py which are not used.

* `is_prime()` is only used in `prime_ge`, which is not used anywhere else.
* `i4_uniform()` is not used anywhere else

The less code we have, the less we need to maintain.

**Comment by Stefan-Endres** [comment]
I was getting some strange import errors when I tried to run the unittests where it's searching for a missing attribute of the module even though we just import everything with *. I've changed the way these functions functions are imported and removed these functions in dcbf6f9491b3fbf8584fc4acba2c98628c2e62b0.

**Comment by alchemyst** [comment]
I think the issue is that you didn't remove the functions from the `__all__` for the module.

**Comment by alchemyst** [comment]
I've removed one more function and updated __all__ in de59e0d0df1e70b07b7efefad891492e181cae54

**Comment by Stefan-Endres** [comment]
Ah, thank you!
