### ISSUE TITLE
Fix coverage on coveralls

### ISSUE THREAD

**Issue by alchemyst** [Stefan-Endres/shgo#14]
Coveralls appears to be tracking only the coverage of the test script itself, not the other files. This is why we had such great coverage to begin with and why it has dropped a lot now, since the tests are not all running (see #13).

We need to make it so that the coverage is tracked across all files in the project not just the test script.

**Comment by Stefan-Endres** [comment]
This has been an issue for a while now, It's supposed to only be tracking `_shgo.py` (88%), the `triangulation.py` (66%) has print and plotting functions that I either need to skip the cosmetic lines or write tests for (or move to another file).
