### ISSUE TITLE
Avoid using `is` to check string equality

### ISSUE THREAD

**Issue by alchemyst** [Stefan-Endres/shgo#22]
There are a couple of places in the code where we use `is` to check for string equality, so 

    if a is 'teststring':
        # whatever

This is not guaranteed to work for all strings as it relies on an implementation detail in cpython (where small strings are cached. It should be taken away wherever it is used.

**Comment by Stefan-Endres** [comment]
Couldn't find any more instances of this after the refactoring in c5ef42f8bd6c37ec2f7d33135b241b06d4613900.

**Comment by alchemyst** [comment]
There are still some in `_shgo_lib/_complex.py` (see for instance [here](https://github.com/Stefan-Endres/shgo/blob/master/shgo/_shgo_lib/_complex.py#L3451))

**Comment by Stefan-Endres** [comment]
Fixed with 9b206ee0bfe8bcc9bcaecad0ea508e609c0fc289
