### ISSUE TITLE
The skip argument is not consistently handled in sobol_points_*

### ISSUE THREAD

**Issue by alchemyst** [Stefan-Endres/shgo#24]
The code expects to pass a skip argument to `sobol_points`, but `sobol_points_10k` doesn't accept such an argument.

This shows two things:
- This will break in high dimensions
- We don't have a test which breaks with this problem right now

**Comment by Stefan-Endres** [comment]
Since moving to `scipy.stats.qmc` this issue is no longer relevant after upstream fixes, closing.
