### ISSUE TITLE
Code requires 3.6

### ISSUE THREAD

**Issue by alchemyst** [Stefan-Endres/shgo#3]
I think it's fine to run only on Python 3, but currently the code fails on 3.5, which is still quite a large installed base. We can use Travis or Tox to test for different version compatibility.

**Comment by Stefan-Endres** [comment]
I believe that SciPy also requires 2.7 compatibility. So we will try to get shgo to run on Python 2.7, 3.5 and 3.6. In general I believe most of the incompatible is easily changeable formatted strings (for dev prints) that were introduced in Python 3.6.

**Comment by Stefan-Endres** [comment]
Fixed with PR merge 602c9cc. Thank you.
